# Server Configuration
server.port=8080

# Spring Application Name
spring.application.name=Restock API

# MongoDB Configuration
spring.mongodb.uri=mongodb://localhost:27017
spring.mongodb.database=restock_db
spring.data.mongodb.auto-index-creation=true

# Application Information for Documentation
# Elements take their values from maven pom.xml build-related information

# Custom Properties for Documentation
# suppress inspection "SpringBootApplicationProperties"
documentation.application.description=@project.description@
# suppress inspection "SpringBootApplicationProperties"
documentation.application.version=@project.version@

# Security autoconfiguration is handled by WebSecurityConfiguration

# JWT Configuration Properties
# Custom Properties for JWT
# suppress inspection "SpringBootApplicationProperties"
authorization.jwt.secret=WriteHereYourSecretStringForTokenSigningCredentials
# suppress inspection "SpringBootApplicationProperties"
authorization.jwt.expiration.days=7

# Springdoc OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Cloudinary Configuration Properties
cloudinary.cloud-name=dplnowmib
cloudinary.api-key=878197382771939
cloudinary.api-secret=ggv-8EF1qsNbIiyWQeAKKs2GB38

# Firebase Configuration Properties
integrations.fcm.enabled=true
# firebase.credentials.base64=ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAidWl0b3BpYy0xNDA2YyIsCiAgInByaXZhdGVfa2V5X2lkIjogIjk5OTUzNzFlMWQzZGZjOGY3NDkxNjQzNjEzZjI1ZmNmNmQ2NDNlYTgiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRREFGektGRE5SMkh6UnNcbnQxZVE4TnVWK21FR1BjTERrUzlaRUxnU3hMYmVWV3FBN28rMVN2UnUyWFZ1Y1VpOWxOclN4YlpCbWR1UzJOQWxcbkYzNmZTeHArQnY4dUxuaFI2dWwzSzZnSE9mNzRhV0dXUGJ5ZFB4Q2xvcGxVTENiYzRFS29QT0w5R3VCTDFzYlJcbmsycUdNdXk3blJ4UVMrcFBRUUhCVFVKTld4Q3pXbjQzYnR0V2hrSWl4d2hSYWJUZ0dEMWdkeHF6TVlwRXpTVjlcbkJKbnZDakJPYnpINFRJOVRSa3BreTBnNkdDMU1wWVBra0RIV0t6MUNueHVkSW5lUjlyYkRKZzlHSDNGQUtVZGpcbmVNVkl6c2VhcFRCZGVnMGdLKytmSnFGeXJTb0h2L0JyUWhUQWtXOW1nOGRtRVErelFHMThBZGE4cFU1Zk9keDBcbnQwZlRQK2w1QWdNQkFBRUNnZ0VBSUFlK05ORmUzQk4zK21qWUFTTW9lbW0xcEFUSVpUUGdZVW1ZYUFqRk5XMm9cbnhMY0MzNGdRR2l2SW1SSHF2eklEQ3dKTTBjT0dDWVo5cnJHc080T2FkMGxUWTYvOEFDemJvVE4yWVQ0YWRmR2NcbmhDRG5RcEV4aFcwSGhER1lpVndid1ZIbHg2NmptQUhJUlVuL2lVRVVtSFFxTkhsMEtLTCtWKzA2RVF3T1RObVFcbkVFTnREcWFFRnYzRGFFT2NkVWw1eitSVUtNV2JXSW55VG1JMEtQSTFMS0s0SDhFQU5OSDNoR09iUmlUaVhidXdcbmxOZXFjTmpaNERydlp0UzRqTDg1QWYzNmhDTmxwaUxBSHZmQ3lUbDZ5NTljUnVSWEdZbVgvRzI1eXJXTjkvTnBcblQ3VUhxOXFZMUpXdHJicFFsb1ExV0VjUWlMeXBlcitGcEFjeUQrckRBUUtCZ1FEbVhHb2NmWThIYWFGV3c5d2FcbjE2R1hrWkFvdStCYXBteVZ0SFEvbklSSkRJcDQ3S1RpT0RaWnprM0RBSlR4d09pM3FXTWJPMjkyN2pMQlgyZUpcbmd1WGpHc3VwazhXMzFMRFp2RjF0RThCMFlzODJJVjBEcWl5eEVKV1FxbEdSVGVYbG9lUVBoazllMTQwb3FxQXlcbkhrNjFwWDJZU2J5RVFOdDRNTWYxczVFQ3RRS0JnUURWZUZ3ai85enRrYjkvNzVjOGZzUkJnenVQRlJMZXM1NG5cbkE2M25YZjVEZlUzdlZnZWhXWnNWSzhnZDYrdjdaQTFzUS9xQk9sUVM5RnQranBnV0lUL3JQaDNDT2hWSFFJdGxcbnZjazM4eXozUkxkdXFBdlhxUFMydTJrd2NjcFcwUTdjbkcyWEFydGxTVWhHOGZvV2lOWjBGQklYMk96Y1Q2STVcbmMveEw5Y2N5TlFLQmdDMytVNTFlb0ZrTmlRNEd5d0o4L1NHRENiSm9XSklnMmx0RmpWUktEc3Q2K29iTVVOdHRcbjk4UVVnY2dtYkphY09wcTQ4alcwdHp1YXNYMlVhOXF6ek94OEpCKzJobXAreDlTaFhGSHorS0FFUG5VRFVrdnlcbkJUeFJJRnVpOWVnNkVtVzMzZzRQZGZkc3VCMWZlOTZsMkhkQ0ZJSjhibXhGZXN4VGlRa1FraXBsQW9HQkFKb1JcbldFOFRKNXkvQ0h1SnJKbVkxSVNEOXNSNTdUaVdZcHE5NlJHSG9TK01qR2NrckRVanV1NDR2eUg1V0VRRUhqdjVcbmhCOG92ZTFBTjVqTHliQ1BKdGJkNmhSNFgwc2hwbm96MDdweDVBNUNwakZUVDlqQ3RIditIeGs3eDFHSmFUU0lcbklnQlBsSGl4djF5VTRHN0xMQnh6TCt2T1FJVnhaQ0FiT2dpSXhzL1JBb0dCQUwxbmQwSVFKZmN1T2hTMkJIQjRcblEvTTQ5aERZc2MrbzNJTGUwOUt3TjJHYzJ6MGZHMjI3UGNxdzQ3VVRuR0VsWUNWMjVyL2Z4Mi91YWZ2dEFRRDZcbmNZZytibFVlaFBqcjZwUEFBeHU2OGh3TU14RmxJbXBza0ZzRFJsTm1GRWx5aHplVEM0M0xxNzVTM2I2d1N0d1NcblVpR04xSVVkUmVXby9zZm5ZM1ZERnJmblxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImZpcmViYXNlLWFkbWluc2RrLWZic3ZjQHVpdG9waWMtMTQwNmMuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTEzNTA4NzU0Nzk4ODc4MzYxMjM1IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9maXJlYmFzZS1hZG1pbnNkay1mYnN2YyU0MHVpdG9waWMtMTQwNmMuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0=
firebase.project.id=uitopic-1406c
firebase.credentials.path=classpath:firebase/uitopic-1406c-firebase-adminsdk-fbsvc-9995371e1d.json

# Resend API Configuration
resend.api.key=re_VSUnc6L1_DFz6xyiMMYHGsMgCcU7f6zxY

# Edge Service Configuration
edge.service.url=http://127.0.0.1:5000/api/v1
edge.service.iam.url= /auth/sign-up
edge.service.device-thresholds.url=/devices/{device_id}/thresholds

# Stripe Configuration
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=whsec_WebhookSecretPlaceholderSecretKey
stripe.success.url=http://localhost:4200/subscriptions/success?session_id={CHECKOUT_SESSION_ID}
stripe.cancel.url=http://localhost:4200/subscriptions/cancel
