# Server Configuration
server.port=${PORT:8080}

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}
spring.data.mongodb.auto-index-creation=true

# Cloudinary Configuration Properties
cloudinary.cloud-name=duasujxja
cloudinary.api-key=777268677726317
cloudinary.api-secret=REngcEDYiqBf_xKJHTJQQWR7hls

# Firebase Configuration Properties
integrations.fcm.enabled=true
firebase.project.id=uitopic-1406c
firebase.credentials.path=C:/Users/gabyn/productos-cursos/productos-iot/restock-web-services/src/main/resources/firebase/uitopic-1406c-firebase-adminsdk-fbsvc-9995371e1d.json

# Resend API Configuration
resend.api.key=${RESEND_API_KEY:}