# Server Configuration
server.port=${PORT:8080}

# MongoDB Configuration
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=${MONGODB_DATABASE}
spring.data.mongodb.auto-index-creation=true

# Cloudinary Configuration Properties
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Firebase Configuration Properties
integrations.fcm.enabled=${INTEGRATIONS_FCM_ENABLED}
firebase.project.id=${FIREBASE_PROJECT_ID}
firebase.credentials.base64=${FIREBASE_CREDENTIALS_BASE64}

# Resend API Configuration
resend.api.key=${RESEND_API_KEY}